services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - 8081:8080
    volumes:
      - ./swagger/swagger.yaml:/swagger.yaml
    environment:
      SWAGGER_FILE: /swagger.yaml
      
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 8082:8080
    volumes:
      - ./swagger/swagger.yaml:/swagger.yaml
    environment:
      SWAGGER_JSON: /swagger.yaml