openapi: 3.0.0
info:
  title: Task management system
  description: This is a sample Task management system based on the OpenAPI 3.0 specification.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1

servers:
  - url: http://localhost:9000/api/v1
    description: Dev server

paths:
  /tasks:
    $ref: api/tasks/tasks.yaml#/paths/~1tasks

  /tasks/{taskId}:
    $ref: api/tasks/byTaskId.yaml

  /tasks/by-assignee/{userId}:
    $ref: api/tasks/byAssigneeId.yaml

  /tasks/by-author/{userId}:
    $ref: api/tasks/byAuthorId.yaml

  /tasks/by-status/{status}:
    $ref: api/tasks/byStatus.yaml

  /tasks/search:
    $ref: api/tasks/search.yaml

  /users:
    $ref: api/users/users.yaml#/paths/~1users

  /users/{username}:
    $ref: api/users/byName.yaml#/paths/~1users~1{username}

  /users/{userId}:
    $ref: api/users/byId.yaml#/paths/~1users~1{userId}

components:
  schemas:
    TaskStatus:
      $ref: schemas/task.yaml#/components/schemas/TaskStatus

    TaskPriority:
      $ref: schemas/task.yaml#/components/schemas/TaskPriority

    Task:
      $ref: schemas/task.yaml#/components/schemas/Task

    CreateTaskRequest:
      $ref: schemas/task.yaml#/components/schemas/CreateTaskRequest

    UpdateTaskRequest:
      $ref: schemas/task.yaml#/components/schemas/UpdateTaskRequest

    UserRole:
      $ref: schemas/user.yaml#/components/schemas/UserRole

    User:
      $ref: schemas/user.yaml#/components/schemas/User

    CreateUserRequest:
      $ref: schemas/user.yaml#/components/schemas/CreateUserRequest

    UpdateUserRequest:
      $ref: schemas/user.yaml#/components/schemas/UpdateUserRequest

    Error:
      $ref: schemas/error.yaml#/components/schemas/Error

