openapi: 3.0.0
info:
  title: Task management system
  description: This is a sample Task management system based on the OpenAPI 3.0 specification.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1

servers:
  - url: http://localhost:9000/api/v1
    description: Dev server

paths:
  /tasks:
    $ref: './paths/tasks.yaml'

  /tasks/{taskId}:
    $ref: './paths/tasksByTaskId.yaml'

  /tasks/by-assignee/{userId}:
    $ref: './paths/tasksByAssigneeId.yaml'

  /tasks/by-author/{userId}:
    $ref: './paths/tasksByAuthorId.yaml'

  /tasks/by-status/{status}:
    $ref: './paths/tasksByStatus.yaml'

  /tasks/search:
    $ref: './paths/tasksSearch.yaml'

  /users:
    $ref: './paths/users.yaml'

  /users/{username}:
    $ref: './paths/usersUserName.yaml'

  /users/{userId}:
    $ref: './paths/usersUserId.yaml'

components:
  schemas:
    TaskStatus:
      $ref: components/task.yaml#/components/schemas/TaskStatus

    TaskPriority:
      $ref: components/task.yaml#/components/schemas/TaskPriority

    Task:
      $ref: components/task.yaml#/components/schemas/Task

    CreateTaskRequest:
      $ref: components/task.yaml#/components/schemas/CreateTaskRequest

    UpdateTaskRequest:
      $ref: components/task.yaml#/components/schemas/UpdateTaskRequest

    UserRole:
      $ref: components/user.yaml#/components/schemas/UserRole

    User:
      $ref: components/user.yaml#/components/schemas/User

    CreateUserRequest:
      $ref: components/user.yaml#/components/schemas/CreateUserRequest

    UpdateUserRequest:
      $ref: components/user.yaml#/components/schemas/UpdateUserRequest

    Error:
      $ref: components/error.yaml#/components/schemas/Error

