paths:
  /tasks/by-assignee/{userId}:
    get:
      operationId: getTasksByAssigneeId
      summary: "Get tasks by Assignee ID"
      tags:
        - Task
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Tasks found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../../schemas/task.yaml#/components/schemas/Task'
        '400':
          description: 'Bad request, invalid assigneeId'
        '404':
          description: 'No tasks found for the specified assigneeId'
        '500':
          description: 'Internal server error'