name: Java CI with Gradle

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - uses: actions/setup-java@v4
        name: Setup JAVA
        with:
          java-version: '17.0.11'
          distribution: 'temurin'

      - name: Build and Test with Gradle
        run: ./gradlew test

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/ 
