name: Java CI with Maven

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - uses: actions/setup-java@v4
        name: Setup JAVA
        with:
          java-version: '17.0.11'
          distribution: 'temurin'

      - name: Build and test with Maven
        run: mvn -B test

      - name: List JaCoCo report directory
        run: ls -R target/site/jacoco/

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
